# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:29:37+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel


class Data(BaseModel):
    token: str


class Response(BaseModel):
    data: Dict[str, Any]
    success: bool


class AuthenticationTokenResponse(Response):
    data: Optional[Data] = None
